# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - path: .
    - requirements: requirements.txt
    - requirements: pydata-sphinx-theme, sphinx-toolbox